export const GET_CATEGORIES = "GET_CATEGORIES";
export const GET_CATEROGY = "GET_CATEROGY";
export const CHANGE_SELECTED_CATEGORY = "CHANGE_SELECTED_CATEGORY";

export const REGISTRY_UPDATE = "REGISTRY_UPDATE";
export const GET_ERROR = "SET_ERROR";
