export const GET_ALL_LISTS = "GET_ALL_LISTS";
export const GET_LIST = "GET_LIST";
export const CHANGE_SELECTED_LIST = "CHANGE_SELECTED_LIST";

export const REGISTRY_UPDATE = "REGISTRY_UPDATE";
export const GET_ERROR = "GET_ERROR";

export const GET_USER = "GET_USER";
export const LIST_CREATED_SUCCESS = "LIST_CREATED_SUCCESS";
