export const GET_CATEGORIES = 'GET_CATEGORIES'
export const GET_CATEGORIES_SUCCESS = 'GET_CATEGORIES_SUCCESS'
export const GET_CATEGORIES_ERROR = 'GET_CATEGORIES_ERROR'

export const REMOVE_CATEROGY = 'REMOVE_CATEROGY'
export const REMOVE_CATEROGY_SUCCESS = 'REMOVE_CATEROGY_SUCCESS'
export const REMOVE_CATEROGY_ERROR = 'REMOVE_CATEROGY_ERROR'

export const GET_CATEROGY_LISTS = 'GET_CATEROGY_LISTS'
export const GET_CATEROGY_LISTS_SUCCESS = 'GET_CATEROGY_LISTS_SUCCESS'
export const GET_CATEROGY_LISTS_ERROR = 'GET_CATEROGY_LISTS_ERROR'

export const UPDATE_CATEGORY_ITEM = 'UPDATE_CATEGORY_ITEM'
export const UPDATE_CATEGORY_ITEM_SUCCESS = 'UPDATE_CATEGORY_ITEM_SUCCESS'
export const UPDATE_CATEGORY_ITEM_ERROR = 'UPDATE_CATEGORY_ITEM_ERROR'

export const ADD_CATEGORY_ITEM = 'ADD_CATEGORY_ITEM'
export const ADD_CATEGORY_ITEM_SUCCESS = 'ADD_CATEGORY_ITEM_SUCCESS'
export const ADD_CATEGORY_ITEM_ERROR = 'ADD_CATEGORY_ITEM_ERROR'

export const REMOVE_CATEGORY_ITEM = 'REMOVE_CATEGORY_ITEM'
export const REMOVE_CATEGORY_ITEM_SUCCESS = 'REMOVE_CATEGORY_ITEM_SUCCESS'
export const REMOVE_CATEGORY_ITEM_ERROR = 'REMOVE_CATEGORY_ITEM_ERROR'
